version: '3.8'

services:
  db:
    image: postgres:17.4
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["python", "app.py"]

volumes:
  pgdata:
